const $=id=>document.getElementById(id), history={x:[],rssi:[],motion:[],amps:[]}; let latest=null,pending=null,lastDraw=0,recordingWasActive=false;
const layout={autosize:true,paper_bgcolor:'transparent',plot_bgcolor:'transparent',font:{color:'#9eb1c8'},margin:{t:15,r:15,b:42,l:52},xaxis:{gridcolor:'#203148',automargin:true},yaxis:{gridcolor:'#203148',automargin:true}};
const plotConfig={responsive:true,displaylogo:false,scrollZoom:false};
function error(e){$('error').textContent=e?.message||String(e)} async function api(path,opts={}){const r=await fetch(path,{headers:{'Content-Type':'application/json'},...opts});if(!r.ok){let d;try{d=await r.json()}catch{}throw Error(d?.detail||`${r.status} ${r.statusText}`)}return r.json()}
function fmt(v,d=2){return Number.isFinite(v)?Number(v).toFixed(d):'—'}
function processed(a){let from=Math.max(0,+$('from').value||0),to=Math.min(a.length,+$('to').value||a.length),v=a.slice(from,to),x=v.map((_,i)=>i+from);if($('removezero').checked){let keep=v.map((n,i)=>n!==0?i:-1).filter(i=>i>=0);x=keep.map(i=>x[i]);v=keep.map(i=>v[i])}let w=Math.max(1,+$('smooth').value||1);if(w>1)v=v.map((_,i)=>{let s=v.slice(Math.max(0,i-w+1),i+1);return s.reduce((a,b)=>a+b,0)/s.length});if($('normalize').checked&&v.length){let m=v.reduce((a,b)=>a+b,0)/v.length,sd=Math.sqrt(v.reduce((a,b)=>a+(b-m)**2,0)/v.length);v=v.map(n=>sd?(n-m)/sd:0)}return{x,v}}
function renderLatest(){if(!latest)return;let q=processed(latest.amplitude);Plotly.react('amplitude',[{x:q.x,y:q.v,type:'scatter',mode:'lines',name:'amplitude'}],layout,plotConfig)}
function drawPacket(p){latest=p;$('nodata').hidden=true;[['rssi',p.rssi],['noise',p.noise_floor],['agc',p.agc_gain],['fft',p.fft_gain],['channel',p.channel],['length',p.csi_length]].forEach(([id,v])=>$(id).textContent=v??'—');let f=p.features||{};[['mean',f.mean_amplitude],['std',f.std_amplitude],['median',f.median_amplitude],['variance',f.variance_amplitude],['difference',f.frame_difference]].forEach(([id,v])=>$(id).textContent=fmt(v));renderLatest();let t=p.received_at;history.x.push(t);history.rssi.push(p.rssi);history.motion.push(p.motion_score);let picks=[.1,.2,.3,.4,.55,.65,.75,.9].map(n=>Math.min(p.amplitude.length-1,Math.floor(n*p.amplitude.length)));history.amps.push(picks.map(i=>p.amplitude[i]));if(history.x.length>300)Object.values(history).forEach(a=>a.shift());Plotly.react('history',picks.map((idx,j)=>({x:history.x,y:history.amps.map(a=>a[j]),mode:'lines',name:`SC ${idx}`})),layout,plotConfig);Plotly.react('motion',[{x:history.x,y:history.motion,mode:'lines',connectgaps:false}],layout,plotConfig);Plotly.react('rssihistory',[{x:history.x,y:history.rssi,mode:'lines'}],layout,plotConfig)}
function schedulePacket(p){pending=p;let wait=Math.max(0,125-(performance.now()-lastDraw));if(schedulePacket.timer)return;schedulePacket.timer=setTimeout(()=>{schedulePacket.timer=null;let next=pending;pending=null;lastDraw=performance.now();if(next)drawPacket(next)},wait)}
async function ports(){try{let ps=await api('/api/ports'),old=$('port').value;$('port').innerHTML='<option value="">Select RX serial port</option>'+ps.map(p=>`<option value="${p.device}">${p.device} — ${p.description}</option>`).join('');$('port').value=old}catch(e){error(e)}}
async function status(){try{let s=await api('/api/status'),x=s.serial;$('status').textContent=x.connected?'Connected':'Disconnected';$('status').className='badge '+(x.connected?'on':'off');$('packets').textContent=x.packet_count;$('rate').textContent=fmt(x.packets_per_second,1);$('rejected').textContent=x.rejected_count;if(x.error)error(x.error);if(x.connected&&x.seconds_since_last_packet!==null&&x.seconds_since_last_packet>3)$('nodata').hidden=false;let r=s.recording;if(!r.active){let done=r.last_result?.stop_reason==='automatic';$('recstate').textContent=done?`Completed automatically · ${r.last_result.packet_count} packets`:'Not recording'}else if(r.state==='countdown')$('recstate').textContent=`Starting in ${Math.max(1,Math.ceil(r.countdown_remaining))}s — move to the test position`;else{let elapsed=Math.min(r.duration_seconds,Math.max(0,Math.floor((Date.now()-Date.parse(r.started_at))/1000)));$('recstate').textContent=`Recording ${elapsed}s / ${r.duration_seconds}s · ${r.packet_count} packets`}$('start').disabled=r.active;$('stop').disabled=!r.active;if(recordingWasActive&&!r.active)await recordings();recordingWasActive=r.active}catch(e){error(e)}}
function ws(){let s=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws/live`);s.onmessage=e=>{let m=JSON.parse(e.data);if(m.type==='packet')schedulePacket(m.data)};s.onclose=()=>setTimeout(ws,1000)}
$('refresh').onclick=ports;$('connect').onclick=async()=>{try{error('');await api('/api/connect',{method:'POST',body:JSON.stringify({port:$('port').value})});connectedAt=Date.now();await status()}catch(e){error(e)}};$('disconnect').onclick=async()=>{try{await api('/api/disconnect',{method:'POST'});await status()}catch(e){error(e)}};
$('start').onclick=async()=>{try{await api('/api/recordings/start',{method:'POST',body:JSON.stringify({label:$('label').value,notes:$('notes').value,delay_seconds:10,duration_seconds:30})});await status()}catch(e){error(e)}};$('stop').onclick=async()=>{try{await api('/api/recordings/stop',{method:'POST'});await status();await recordings()}catch(e){error(e)}};
async function recordings(){try{let rs=await api('/api/recordings');$('recordings').innerHTML='<option value="">Choose a recording</option>'+rs.map(r=>`<option value="${r.filename}">${r.filename} · ${r.label||'unknown'}</option>`).join('')}catch(e){error(e)}}
$('reload').onclick=recordings;$('load').onclick=async()=>{try{let d=await api('/api/recordings/'+encodeURIComponent($('recordings').value)),p=d.packets;$('details').textContent=JSON.stringify({filename:d.filename,packets_loaded:p.length,truncated:d.truncated,label:p[0]?.session_label??null,notes:p[0]?.session_notes??null,started_at:p[0]?.session_timestamp??null},null,2);Plotly.react('replay',[{x:p.map(x=>x.received_at),y:p.map(x=>x.motion_score),name:'motion score',mode:'lines'}],layout,plotConfig)}catch(e){error(e)}};
$('export').onclick=()=>{let name=$('recordings').value;if(!name){error('Choose a recording before exporting CSV.');return}error('');location.href='/api/recordings/'+encodeURIComponent(name)+'/csv'};
['from','to','normalize','smooth','removezero'].forEach(id=>$(id).onchange=renderLatest);ports();recordings();status();setInterval(status,1000);ws();
